"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const faqs = [
  {
    question: "How does SkuPilot enrich product content?",
    answer:
      "SkuPilot uses a multi-step AI pipeline powered by Claude claude-sonnet-4-6 and GPT-4o. It takes your raw product data, normalises it into a structured schema, then generates SEO-optimised titles, rich descriptions, bullet-point features, and complete attribute sets — all in your brand's voice. Images are generated by Flux Pro, videos by Runway ML, and translations are handled by DeepL.",
  },
  {
    question: "What input formats does SkuPilot accept?",
    answer:
      "SkuPilot accepts CSV uploads, product page URLs (we use Firecrawl to scrape them automatically), raw attribute pastes, and direct API calls. If you have a Shopify, Amazon, or Magento store, you can connect it directly and import your entire existing catalog with one click.",
  },
  {
    question: "How long does enrichment take per product?",
    answer:
      "Text enrichment (title, description, features, attributes, meta) takes under 30 seconds per product. Image generation (5 images) takes 60–90 seconds. Video generation takes 3–5 minutes. Translation into 40+ languages takes another 30–60 seconds. The entire pipeline runs in parallel in the background — you can continue working while it processes.",
  },
  {
    question: "Can I customise SkuPilot to match my brand voice?",
    answer:
      "Yes. Every organisation has a Brand Voice configuration where you can set your tone (professional, playful, technical, luxury), target audience, taboo words, and even provide sample content for SkuPilot to learn from. The Claude prompt template is built around this brand voice and applied consistently across every product in your catalog.",
  },
  {
    question: "Which platforms can I publish to?",
    answer:
      "SkuPilot natively integrates with Shopify (via Admin REST + GraphQL API), Amazon Seller Central (via SP-API), and Magento 2 (via REST API). You can also export a clean CSV formatted for any other platform, or use the webhook API to push enriched data to any custom endpoint.",
  },
  {
    question: "Is my product data secure?",
    answer:
      "All product data is encrypted at rest (AES-256) and in transit (TLS 1.3). We use Neon PostgreSQL for structured data and Cloudflare R2 for generated assets. We never share your data with third parties or use it to train AI models. Your data belongs to you — you can export or delete it at any time.",
  },
  {
    question: "What happens if the AI generates incorrect content?",
    answer:
      "Every generated field is shown to you in the Product Editor before publishing. You can regenerate any section individually, edit the output manually, or configure SkuPilot to require manual approval before any product goes live. The system also shows a Quality Score so you can immediately spot fields that need attention.",
  },
  {
    question: "Do you offer a free trial?",
    answer:
      "Yes — the Starter plan is free to try for 14 days with no credit card required. You get 50 product enrichments, access to the full AI pipeline, and all platform integrations. After the trial, you can upgrade to a paid plan or your account moves to a read-only state until you decide.",
  },
];

export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section id="faq" className="section-padding bg-white">
      <div className="container-section">
        <div className="text-center mb-16">
          <span className="section-label mb-4 block">FAQ</span>
          <h2 className="mb-4">
            Frequently Asked <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto">
            Everything you need to know about SkuPilot. Can&apos;t find the
            answer?{" "}
            <a
              href="mailto:hello@skupilot.ai"
              className="text-sky-600 hover:underline"
            >
              Email us
            </a>
            .
          </p>
        </div>

        <div className="max-w-3xl mx-auto space-y-3">
          {faqs.map((faq, i) => (
            <div
              key={i}
              className="bg-white border border-slate-200 rounded-xl overflow-hidden transition-shadow hover:shadow-sm"
            >
              <button
                onClick={() => setOpenIndex(openIndex === i ? null : i)}
                className="w-full flex items-center justify-between px-6 py-5 text-left gap-4"
                aria-expanded={openIndex === i}
                aria-controls={`faq-answer-${i}`}
                id={`faq-question-${i}`}
              >
                <span className="font-semibold text-slate-800 text-sm sm:text-base">
                  {faq.question}
                </span>
                <ChevronDown
                  className={cn(
                    "w-5 h-5 text-slate-400 flex-shrink-0 transition-transform duration-300",
                    openIndex === i && "rotate-180 text-sky-500"
                  )}
                />
              </button>

              <div
                id={`faq-answer-${i}`}
                role="region"
                aria-labelledby={`faq-question-${i}`}
                className={cn(
                  "overflow-hidden transition-all duration-300 ease-in-out",
                  openIndex === i ? "max-h-96" : "max-h-0"
                )}
              >
                <div className="px-6 pb-6 text-slate-600 text-sm leading-relaxed border-t border-slate-100 pt-4">
                  {faq.answer}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
